neutrinolabs/xorgxrdp

- xrdpdev/xrdpdev.c
On "Raspberry PI 3 Model B", pScrn->numEntities equal 2.
> Fix for Raspberry PI 3 Model B

- module/amd64/a8r8g8b8_to_a8b8g8r8_box_amd64_sse2.asm
- module/amd64/a8r8g8b8_to_nv12_box_amd64_sse2.asm
- module/amd64/cpuid_amd64.asm
- module/amd64/i420_to_rgb32_amd64_sse2.asm
- module/amd64/uyvy_to_rgb32_amd64_sse2.asm
- module/amd64/yuy2_to_rgb32_amd64_sse2.asm
- module/amd64/yv12_to_rgb32_amd64_sse2.asm
- module/x86/a8r8g8b8_to_a8b8g8r8_box_x86_sse2.asm
- module/x86/a8r8g8b8_to_nv12_box_x86_sse2.asm
- module/x86/cpuid_x86.asm
- module/x86/i420_to_rgb32_x86_sse2.asm
- module/x86/uyvy_to_rgb32_x86_sse2.asm
- module/x86/yuy2_to_rgb32_x86_sse2.asm
- module/x86/yv12_to_rgb32_x86_sse2.asm
This is a more portable alternative to #11 
The fix is described at https://wiki.gentoo.org/wiki/Hardened/GNU_stack_quickstart
The fix was tested by running the command that rpmlint runs: `readelf -W -S -l -d -s libxorgxrdp.so` and checking that "E" is not in the flag column for the GNU_STACK headers.
> Mark stack non-executable in *.asm files

- module/amd64/yv12_to_rgb32_amd64_sse2.asm
- module/x86/yv12_to_rgb32_x86_sse2.asm
That's another compile fix for an issue caused by the latest patches. NASM uses `%` rather than `#` for the preprocessor.
> Use correct notation for NASM preprocessor

- module/rdp.h
- module/rdpClientCon.c
- module/rdpRandR.c
- xrdpdev/xrdpdev.c
monitorResolution is 0 if DPI is not specified on the Xorg command line, so it should not be used without checking.
This patch respects the horizontal and the vertical DPI in case they are different.
> Use xDpi and yDpi instead of monitorResolution

- xrdpkeyb/rdpKeyboard.c
There is no nice function or macro for that. Do what Xorg code does.
> Memory leak fix - free result of XkbGetCoreMap()

- module/rdpRandR.c
gtk3 programs crash when they divide dotClock by hTotal and vTotal to
calculate the refresh rate.
That is not an issue if Xorg supports RandR 1.5, but may be an issue for
older versions of Xorg.
> Provide reasonable hTotal, vTotal and dotClock for the display mode

- module/rdpClientCon.c
- module/rdpCursor.c
- module/rdpDraw.c
- module/rdpInput.c
- xrdpdev/xrdpdev.c
This PR improves the cleanup when Xorg exits. Changes are mostly for code quality. A few hacks have been removed. The screen-related cleanup doesn't depend on the cursor or input code anymore. Valgrind won't complain of leaked file descriptors.
The teardown function is not called for non-input devices. That's still the case. The xorgxrdp module has a function `xorgxrdpTearDown` that is not called. Hopefully we fix teardown one day, and then it will be called. Another function, `xorgxrdpDownDown` is called manually to do the cleanup.
`xorgxrdpDownDown` was called from the cursor code. It is strange and unreliable. Older RHEL 6 based systems don't call that function.
Instead, `xorgxrdpDownDown` should be called from `rdpCloseScreen`. It turns out that `rdpCloseScreen` was not properly …
> Improve cleanup code

- .travis.yml
"make distcheck" runs in a subdirectory, so it could not find xrdp headers using relative path.
> Use absolute path in PKG_CONFIG_PATH to fix "make distcheck"

- configure.ac
EL6's autoconf is 2.63. bootstrap fails with autoconf < 2.65.
Users can install autoconf 2.68 from EPEL.
```
$ rpm -qa |grep autoconf
autoconf268-2.68-2.el6.noarch
autoconf-2.63-5.1.el6.noarch
$ git clone --branch devel  https://github.com/neutrinolabs/xorgxrdp.git
$ cd xorgxrdp
$ ./bootstrap
/usr/bin/autoconf
/usr/bin/automake
/usr/bin/libtool
/usr/bin/pkg-config
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
/usr/bin/m4:configure.ac:13: recursion limit of 1024 exceeded, use -L<N> to change it
autom4te: /usr/bin/m4 failed with exit status: 1
aclocal: autom4te failed with exit status: 1
autoreconf: aclocal failed with exit status: 1
```
Let user know what should be done, explicitly require autoconf >=2.65.
The …
> Require autoconf >= 2.65

- README.md
Don't use any complex scripts in README. Give information to the users who
downloaded the tarball, not only to those who cloned the repository. Describe
features. Document installation. Move debugging to contributing, it's not part of
standard usage. Mention "tests" directory.
> Make README.md user friendlier

- module/Makefile.am
It makes libtool show an error message. No released version of libtool
has any reference to the NASM tag.
> Don't use "--tag NASM" with libtool

- .travis.yml
- module/amd64/a8r8g8b8_to_a8b8g8r8_box_amd64_sse2.asm
- module/amd64/a8r8g8b8_to_nv12_box_amd64_sse2.asm
- module/amd64/funcs_amd64.h
- module/rdp.h
- module/rdpCapture.c
- module/rdpCapture.h
- module/rdpComposite.c
- module/x86/a8r8g8b8_to_a8b8g8r8_box_x86_sse2.asm
- module/x86/a8r8g8b8_to_nv12_box_x86_sse2.asm
- module/x86/funcs_x86.h
- xrdpkeyb/rdpKeyboard.c
- xrdpmouse/rdpMouse.c
Eliminate all void pointers in rdpCapture.c, use char or const char pointers as needed.
> Fix cppcheck warnings, disallow warnings in Travis CI

- module/Makefile.am
- module/nasm_lt.sh
Remove output from nasm_lt.sh, print "NASM" and target name when silent
rules are enabled.
> Correctly silence nasm compilation

- module/rdpClientCon.c
I believe it makes it easier to debug buffer overrun #9, #62.
> log stream size not only length and connection count

- module/rdpRandR.c
Lower debug level to 10. Print pointers that are actually used by the
function. Don't print crtc, it's not used.
> Suppress useless debug messages from rdpRRGetPanning

- xrdpkeyb/rdpKeyboard.c
Variable i contains MAP_LENGTH, but the allocated block is twice as long,
since GLYPHS_PER_KEY is 2.
> Zeroize all keymap when allocating it, not its first half

- module/rdpMisc.h
Those functions make the X server exit if memory allocation fails.
> Use xnfalloc() and xnfcalloc() for memory allocation

- configure.ac
- module/Makefile.am
- module/amd64/Makefile.am
- module/x86/Makefile.am
- tests/yuv2rgb/.gitignore
- tests/yuv2rgb/Makefile.am
Instead of linking yuv2rgb_speed against a specific object file, link it against a library containing all SIMD accelerated code. That would simplify adding more tests for the assembly code.
> Use makefiles in arch-specific directories, simplify test build

- module/rdpClientCon.c
- module/rdpMisc.c
- module/rdpMisc.h
Needed to support configurable socket directory as implemented in https://github.com/neutrinolabs/xrdp/pull/695
> Use XRDP_SOCKET_PATH environment variable for socket path

- module/amd64/funcs_amd64.h
- module/rdp.h
- module/rdpCapture.c
- module/rdpCapture.h
- module/rdpClientCon.c
- module/rdpClientCon.h
- module/rdpCursor.c
- module/rdpMisc.c
- module/rdpMisc.h
- module/rdpPri.c
- module/rdpRandR.c
- module/rdpXv.c
- module/rdpXv.h
- module/x86/funcs_x86.h
- xrdpdev/xrdpdev.c
clang 3.9.1 produces a warning about casting 255 to char. Fixing that warning lead me to making extensive changes throughout the code.
Xorg uses stdint.h, so it should be OK for xorgxrdp. Take advantage of the types that use the exact bit size. It documents the intent of the code much better.
Add `const` to many more pointers.
Fix an issue in RDPCLAMP macro that made it impossible to cast to another type.
> Use stdint.h, constify more pointers, fix clang warning

- module/rdpCapture.c
- module/rdpClientCon.c
- module/rdpClientCon.h
> keep and use crc calculations for rfx tiles to save bandwidth when an app redraws aggressively

- module/rdpClientCon.c
Allows the use of monitor 0 for the xorgxrdp device.
Properly checks for the difference between monitor `"0"` and the `0` return from `atoi` on invalid data by switching to `strtol`.
> Removes the monitor 0 restriction for xrdpdev

- module/rdpClientCon.c
I've been looking at the issues with running xrdp as a non-root user, and comparing #16, https://github.com/neutrinolabs/xrdp/pull/464 and the debian packaging patches (https://anonscm.debian.org/cgit/pkg-remote/xrdp.git/tree/debian/patches/fix_perms.diff).
I'm contemplating running xrdp as a non-root user on other distros (e.g. redhat) who don't take the step of patching the package, and was hoping this might be fixable upstream?
I appreciate that the project is reluctant to change the permissions/bits on the whole socketdir directory, but was wondering if just this simple change to the socket itself would be acceptable?
Since the code that creates the socketdir does nothing if the socket already exists, it's easy to make the directory with appropriate permissions before starting the …
> Give group write perms to socket.

- module/rdpRandR.c
When using xorgxrdp, a call to XRRGetCtrcGamma() returned a result with a single entry.
This is confusing to some software. For example, gnome-settings-daemon on RHEL/CentOS 7.4 can coredump which takes out the whole session. See:-
https://bugs.centos.org/view.php?id=14054
The coredump is caused by a division of (size-1) where 'size' is the number of entries in the gamma ramp.
This change replaces the single entry gamma ramp with a 256 entry gamma ramp, which seems to be more standard. This is what is implemented in tigervnc-server (see https://github.com/TigerVNC/tigervnc/blob/master/unix/xserver/hw/vnc/xvnc.c ) and also by nouveau on a GTX 470.
> Prevent GNOME 3 gnome-settings-daemon crash on RHEL/CentOS 7.4

- configure.ac
- module/Makefile.am
- module/rdp.h
- xrdpdev/Makefile.am
- xrdpkeyb/Makefile.am
- xrdpmouse/Makefile.am
Now configure.ac is the only place to define version. Pass the version
via Makefile and compiler command line args -Dfoo=bar.
> Don't define package/module version in multiple files

- xrdpdev/xrdpdev.c
Autotools configures xorg-server.h
define XvExtension 1
Meson configures xorg-server.h
define XvExtension
So we just want to test for if XvExtension is defined.
If XVideo is not configured, XvExtension is not defined. You never see
define XvExtension 0
so this should work for all Xorg versions.
> change XvExtension use

- xrdpmouse/rdpMouse.c
This is one of a couple of pull requests to address the memory issues found in #104 by @keithrob91.
This is the simpler of the two and corresponds to the last paragraph of the issue raised.
The second argument of the call to InitPointerDeviceStruct() is an array based at 1, rather than 0. This can be seen in other projects. See for example vncPointerProc() from TigerVNC's [unix/xserver/hw/vnc/Input.c](https://github.com/TigerVNC/tigervnc/blob/master/unix/xserver/hw/vnc/Input.c). The Xorg code on the other end is in [xserver/dix/devices.c](https://cgit.freedesktop.org/xorg/xserver/tree/dix/devices.c)
> Fix invalid memory access in rdpmouseControl()

- module/rdpClientCon.c
- module/rdpClientCon.h
This is the last of a couple of pull requests to address the memory issues found in #104 by @keithrob91.
As mentioned in that request, the `clientCon` is freed whenever `rdpClientConSend()` or `rdpClientConRecv()` detect a connection problem. Not all the code paths are expecting this, and as a result the `clientCon` is potentially accessed after being freed.
One approach would be to go through all the code paths which call `rdpClientConSend()` or `rdpClientConRecv()`  and check they can handle the connection being deleted. I think this is likely to be a bit fiddly and quite brittle to maintain.
The approach I've taken is to remove most of the calls to `rdpClientConDisconnect()` and replace them with clearing a boolean flag `connected` . The actual call to `rdpClientConDisconnect()` now …
> Address invalid memory access (#104) in rdpClientCon

- module/rdp.h
- module/rdpClientCon.c
- module/rdpInput.c
this version does not use fixed 1s timers. it calculates the remaining idle time and sets the timer to calculated value. this way only the minimum of timer eexcutions are needed.
> Idle timer optimized version

- xrdpmouse/rdpMouse.c
associate with [https://github.com/neutrinolabs/xrdp/pull/1478](https://github.com/neutrinolabs/xrdp/pull/1478)
> support button 8/9

- module/rdpClientCon.c
- module/rdpClientCon.h
So I've been doing some [latency testing](https://thume.ca/2020/05/20/making-a-latency-tester/) and tracing of xrdp and I found that after it receives a paint the computer sits idle for 40ms before sending the paint to the client. In xterm depending on the monitor and other factors I can see keyboard-to-screen latencies of 120ms with xrdp, so in those cases the 40ms sleep accounts for 1/3rd of the end-to-end latency.
I tracked it down to a timer that serves dual duty as a hard-coded frame rate limiter (25fps) and a way to wait for any more updates from the app before sending off a packet. 40ms is way longer than is needed to wait for more screen paints, so I split it into two separate delays: an inter-frame delay and a "waiting for more updates" delay. I kept a 4ms delay to wait for more …
> Reduce input lag by 36ms by separating frame rate limiting from update batching

- module/rdpClientCon.c
Killing disconnected sessions should not happen if
XRDP_SESMAN_KILL_DISCONNECTED=0.
Fixes #174.
Signed-off-by: Koichiro IWAO <meta@vmeta.jp>
> Fix bug in kill disconnect sessions

- module/rdpClientCon.c
to know how often deletion of socket files fails.
Related to: neutrinolabs/xrdp#1740
> rdpClientConDeinit: add some logs

- xrdpdev/xorg.conf
Fixes neutrinolabs/xrdp#1784
Another way to do this is to add a `-layout` switch to `/etc/xrdp/sesman.ini`. I'm less keen on this because of the coupling it introduces between the two projects (i.e. xrdp now needs to know the name of the xorgxrdp server layout). Any thoughts on this?
> Add "DefaultServerLayout" option

- module/rdpClientCon.c
Companion PR to neutrinolabs/xrdp#1813
This won't pass CI at the moment for obvious reasons!
Here's the tail of an example xorgxrdp log for a version mismatch:-
```
. . .
[   289.083] expected xrdp client_info version 20210225, got 20210226
[   289.083] (EE)
Fatal server error:
[   289.083] (EE) Incompatible xrdp version detected  - please recompile(EE)
[   289.083] (EE)
Please consult the The X.Org Foundation support
at http://wiki.x.org
for help.
[   289.083] (EE) Please also check the log file at ".xorgxrdp.11.log" for additional information.
[   289.083] (EE)
[   289.083] rdpmouseControl: what 4
[   289.083] rdpkeybControl: what 4
[   289.083] rdpLeaveVT:
[   289.084] (EE) Server terminated with error (1). Closing log file.
```
I've gone for a fatal error as I think this will save …
> Check client_info version from xrdp

- configure.ac
@matt335672 I've changed dependency to require xrdp v0.9.16. Do you think is this valid?
> bump version to v0.2.16
